name: Secrets Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: get-docker-creds
        uses: say8425/aws-secrets-manager-actions@v1.1.1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          SECRET_NAME: common/gh-actions/docker
      - name: Run a one-line script
        run: echo $(env)
      - name: Run a one-line script
        run: echo ${{ secrets }}
